version: 2.1

orbs:
  slack: circleci/slack@3.4.2
  cloudfoundry: circleci/cloudfoundry@0.1.73
  
jobs:
  build:
    docker:
      # 2019-10-23 BTH: had to fix the version as there is a breaking change in latest (=0.59)
      # See https://hub.docker.com/r/cibuilds/hugo, https://github.com/cibuilds/hugo
      - image: cibuilds/hugo:0.58.3
    steps:
      - checkout
      - run:
          name: Install git client
          command: apk update && apk add git
      - run:
          name: Load submodule
          command: git submodule sync && git submodule update --init
      - run:
          name: Build Hugo static website
          command: |
            HUGO_ENV=production hugo
            cp -r public/ /tmp/public
            cp manifest.yml /tmp/
      - store_artifacts:
          path: /tmp/public
      - store_artifacts:
          path: /tmp/manifest.yml
      - persist_to_workspace:
          root: /tmp
          paths:
            - public
            - manifest.yml
      - run:
          name: Test generated HTML files
          command: |
            htmlproofer public/ --allow-hash-href --check-html \
            --empty-alt-ignore --disable-external
      - run: exit 0
      - slack/status:
          fail_only: false
          only_for_branches: 'master'
          webhook: '${SLACK_WEBHOOK}'
  scan:
     docker:
       - image: sonarsource/sonarcloud-scan:1.1.0
     steps:
     - checkout
     - run:
         name: Quality Scan
         command: sonar-scanner -X -Dsonar.host.url=https://sonarcloud.io -Dsonar.login="$SONAR_LOGIN"
     - run: exit 0
     - slack/status:
         fail_only: false
         only_for_branches: 'master'
         webhook: '${SLACK_WEBHOOK}'
         
  test:
     machine: true
     steps:
     - checkout
     - run:
        name: Running k6 tests
        command: |
          docker pull loadimpact/k6:latest 
          docker run -i -e K6_CLOUD_TOKEN=$K6_CLOUD_TOKEN -v $PWD:/ci/ loadimpact/k6:latest cloud /ci/loadtests/performance-test.js
     - run: exit 0
     - slack/status:
         fail_only: false
         only_for_branches: 'master'
         webhook: '${SLACK_WEBHOOK}'
        
  testUI:
      docker:
        - image: circleci/node:13.10.1-browsers
      steps:
        - checkout
        - run:
            name: Browser Testing
            command: |
              npm i selenium-webdriver
              node browser-testing/tech-lunch.js
        - run: exit 0
        - slack/status:
            fail_only: false
            only_for_branches: 'master'
            webhook: '${SLACK_WEBHOOK}'
 
workflows:
  version: 2.1
  build_deploy_tests_and_scan:
    jobs:
      - scan
      - build:
          requires:
            - scan
      - cloudfoundry/blue_green:
          requires:
            - build
          appname: tech-lunch-devops
          domain: cfapps.io
          dark_subdomain: tech-lunch-devops-dev
          live_subdomain: tech-lunch-devops
          workspace_path: /tmp
          manifest: /tmp/manifest.yml
          org: tech-lunch-devops
          package: /tmp/public
          space: development
      - test:
          requires:
            - cloudfoundry/blue_green
      - testUI:
          requires:
            - cloudfoundry/blue_green
 # Scheduled workflows may be delayed by up to 15 minutes.
 # This is done to maintain reliability during busy times such as 12:00am UTC. 
 # Scheduled workflows should not assume they are started with to-the-minute accuracy.
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - scan
      - build
      - cloudfoundry/blue_green:
          requires:
            - build
          appname: tech-lunch-devops
          domain: cfapps.io
          dark_subdomain: tech-lunch-devops-dev
          live_subdomain: tech-lunch-devops
          workspace_path: /tmp
          manifest: /tmp/manifest.yml
          org: tech-lunch-devops
          package: /tmp/public
          space: development
